name: Pull request

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/publish.yml
    strategy:
      fail-fast: false
      matrix:
        python:
          - ["3.11", cp311]
        os_arch:
          - [ubuntu-latest, manylinux_x86_64]
          - [windows-latest, win_amd64]
          - [macos-latest, macosx_arm64] # macos-latest is always arm64 going forward
    with:
      python: ${{matrix.python}}
      os_arch: ${{matrix.os_arch}}
