name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/publish.yml
    strategy:
      fail-fast: false
      matrix:
        python:
          - ["3.11", cp311]
          - ["3.12", cp312]
          - ["3.13", cp313]
        os_arch:
          - [ubuntu-latest, manylinux_x86_64]
          - [windows-latest, win_amd64]
          - [macos-13, macosx_x86_64] # macos-13 is the last x86-64 runner
          - [macos-latest, macosx_arm64] # macos-latest is always arm64 going forward
    with:
      python: ${{matrix.python}}
      os_arch: ${{matrix.os_arch}}
